export const client = {
  name: "Landscape One Design Ltd",
  tagline: "Professional Landscape Designer in Leeds — Quality You Can Trust",
  description: "Professional landscape designer services in Leeds and surrounding areas. Trusted local experts with 3 Google reviews.",
  category: "Landscape Designer",
  yearEstablished: "2015",
  phone: "",
  email: "",
  website: "",
  address: "",
  city: "Leeds",
  county: "",
  postcode: "",
  basedIn: "Leeds",
  founderName: "Noel",
  founderSurname: "",
  founderRole: "Director",
  facebook: "",
  instagram: "",
  linkedin: "",
  twitter: "",
  googleRating: "5",
  reviewCount: "3",
  services: [
    { title: "Garden Design", description: "Bespoke garden designs tailored to your lifestyle and space.", icon: "tree" },
    { title: "Landscaping", description: "Complete hard and soft landscaping to transform your outdoor area.", icon: "shovel" },
    { title: "Paving & Patios", description: "Beautiful paving solutions using premium natural stone and porcelain.", icon: "wall" },
    { title: "Planting Schemes", description: "Year-round colour and interest with expertly curated planting plans.", icon: "flower" },
  ],
  cinematic: {
    frameCount: 181, frameDir: "/frames/", framePrefix: "frame_", frameExtension: ".jpg",
    framePadding: 4, scrollLength: "500vh", mobileFrameCount: 181, mobileFrameDir: "/frames-mobile/",
    scrubSpeed: 0.5, heroStillImage: "/images/hero-still.jpg", heroStillImageMobile: "/images/hero-still-mobile.jpg",
  },
  beforeAfter: { beforeImage: "/images/before.jpg", afterImage: "/images/after.jpg", beforeLabel: "Current Garden", afterLabel: "Our Vision" },
  transformations: [
    { before: "/images/before.jpg", after: "/images/after.jpg", label: "Complete Garden Renovation" },
    { before: "/images/patio-before.jpg", after: "/images/patio-after.jpg", label: "Patio & Fencing" },
    { before: "/images/front-before.jpg", after: "/images/front-after.jpg", label: "Front Garden" },
    { before: "/images/lawn-before.jpg", after: "/images/lawn-after.jpg", label: "Lawn Restoration" },
    { before: "/images/fence-before.jpg", after: "/images/fence-after.jpg", label: "New Fencing" },
    { before: "/images/deck-before.jpg", after: "/images/deck-after.jpg", label: "Decking & Furniture" },
    { before: "/images/path-before.jpg", after: "/images/path-after.jpg", label: "Garden Path" },
    { before: "/images/border-before.jpg", after: "/images/border-after.jpg", label: "Planting Borders" },
    { before: "/images/drive-before.jpg", after: "/images/drive-after.jpg", label: "Driveway" },
  ] as { before: string; after: string; label: string }[],
  reviews: [
    { name: "gerald biggins", rating: 5, text: "Noel and the team at Landscape One did a fantastic job on our small garden, transforming it from a scruffy under appreciated plot into a beautiful outdoor area to relax and enjoy some al fresco dining. They offered some great ideas, worked through some horrendous weather and always kept us in the loop. When the rain warped some fencing they were quick to let us know and sorted it out straight away. We would highly  recommend them.", date: "4 years ago", badge: "Local Guide" },
    { name: "Anthony Hodgson", rating: 5, text: "I found Landscape One from previous projects posted on Houzz. We needed someone to excavate and create a new patio area outside the back of our house. From the start I found Noel great to deal with. He understood what we wanted and provided a great solution with clear communication and costs all the way through the project. Everything Noel and his team did was done to perfection and the finish is exceptional. They were a pleasure to have around for the whole project. I can't find fault with anything they did and I couldn't recommend them highly enough. Noel and Landscape One are fist rate, and i'd be happy to recommend them for any garden design and build project.", date: "5 years ago" },
  ] as { name: string; rating: number; text: string; date: string; badge?: string }[],
  seo: {
    title: "Landscape One Design Ltd | Professional Landscape Designer in Leeds",
    description: "Professional landscape designer in Leeds. 5 stars on Google with 3 reviews. Quality workmanship guaranteed.",
  },
};
